// <auto-generated />
using System;
using FM.REPOSITORIES;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FM.REPOSITORIES.Migrations
{
    [DbContext(typeof(FMContext))]
    [Migration("20190206095216_homegroupfinal")]
    partial class homegroupfinal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FM.DATA.GroupSesionPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupSessionId");

                    b.Property<bool>("IsDelete");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("GroupSessionId");

                    b.HasIndex("PersonId");

                    b.ToTable("GroupSesionPerson");
                });

            modelBuilder.Entity("FM.DATA.GroupSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<bool>("IsDelete");

                    b.HasKey("Id");

                    b.ToTable("GroupSessions");
                });

            modelBuilder.Entity("FM.DATA.HomeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("HomeGroups");
                });

            modelBuilder.Entity("FM.DATA.Mailing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Mailings");
                });

            modelBuilder.Entity("FM.DATA.MailingPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelete");

                    b.Property<int>("MailingId");

                    b.Property<int>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("MailingId");

                    b.HasIndex("PersonId");

                    b.ToTable("MailingPersons");
                });

            modelBuilder.Entity("FM.DATA.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int>("HomeGroupId");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("HomeGroupId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("FM.DATA.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<bool>("IsDelete");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FM.DATA.GroupSesionPerson", b =>
                {
                    b.HasOne("FM.DATA.GroupSession", "GroupSession")
                        .WithMany("GroupSesionPersons")
                        .HasForeignKey("GroupSessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FM.DATA.Person", "Person")
                        .WithMany("GroupSesionPersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FM.DATA.MailingPerson", b =>
                {
                    b.HasOne("FM.DATA.Mailing", "Mailing")
                        .WithMany("MailingPerson")
                        .HasForeignKey("MailingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FM.DATA.Person", "Person")
                        .WithMany("MailingPerson")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FM.DATA.Person", b =>
                {
                    b.HasOne("FM.DATA.HomeGroup", "HomeGroup")
                        .WithMany("People")
                        .HasForeignKey("HomeGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
